## Topic and Concept Descriptions

### Risk

Risk is the estimation of the size and probability of adverse events. The calculation of risk is heavily dependent on assumptions regarding security behavior.   Topics in risk will show different ways to measure, observe, and understand risk in modern markets.

#### A First Look At Risk

This interactive presentation covers how to measure risk in financial markets and the assumptions which go into various measures.  It also lets you investigate how risk differs among securities.

#### Risk Over Time 

This interactive presentation allows you to explore how risk changes dynamically over time, and discusses the implications of time-varying risk. It also looks at market measures of future risk. 

#### The VIX Index

The VIX index is the stock market's *fear gauge*. This presentation discusses the calculation of the VIX, its historical performance, and how it can be used. 

#### VVIX: The Vol of Vol

The VVIX index tracks the volatility of the VIX. This presentation discusses the purpose and performance of the VVIX. 

### Portfolio Finance

Topics in Portfolio Finance cover how to construct portfolios which have the highest return *per unit risk*.  That is, it covers the idea and mathematics of balancing risk and return. Beyond portfolio construction, we also cover portfolio performance measurement and attribution.

#### An Introduction to Portfolio Performance Measures 

How do you rate a portfolio (and portfolio manager's) performance?  We have to balance the portfolio's return, with the risk taken to earn that return, to get the return per unit risk.  However there are various measures of risk, and so various performance measures, which you can explore in this presentation. 

### Corporate Finance

A main goal of Corporate Finance is to learn how to decide whether to invest in a project or not.  Toward this end we learn how to estimate cash flows, move those cash flows in time, and estimate risk on the cash flows.  We then can value stock, bonds, and employ investment decision rules (i.e. NPV and IRR).  

#### An Introduction to Financial Statements

Financial statements report corporate profitability (income statement) and capital structure (balance sheet).  In finance we often use these statements to calculate cash flows for valuations and to estimate how much debt a company can manage. 

#### Financial Ratios

Financial ratios use data contained in financial statements to calculate characteristics of a company.  For example a ratio of total debt divided by total equity is a measure of the firm's leverage.  The ratio controls for firm size, enabling us to compare firms.

#### Time Value of Money: Single Cash Flows

Most analyses in finance, such as valuations, require moving cash flows to different points in time.  This presentation will teach you the mechanics to do so, and also provide interactive elements to help you get an intuitive feel for the interrelationships between time, interest rate, and values.

#### Time Value of Money: Multiple Cash Flows

This presentation covers the valuation of common financial contracts with multiple cash flows such as mortgages (an annuity) and preferred stock (a perpetuity).  Interactive apps are included to value these contracts.

#### Operating Cash Flow

We calculate operating cash flow from financial statements, and it tells us how much cash the firm generates.  The cash flows are used to value the firm, and also determine debt capacity.

#### Net Present Value and Internal Rate of Return

Net present value and the internal rate of return are the two most widely used investment decision rules. They are used by corporations to decide whether to accept a project.   

#### An Introduction to Stock Valuation

A widely used method of stock valuation is by discounting expected dividends.  This presentation will show you how to value stock given varying assumptions about dividend payment structure. The interactive apps will give you an intuitive understanding of how stock values relate to dividends, dividend growth rates, and discount rates.  

#### An Introduction to Bond Valuation

This presentation shows how to value coupon bonds, and provides interactive apps where you can calculate bond values and yield-to-maturities.  

#### The Capital Asset Pricing Model 

The capital asset pricing model is the most widely used way to calculate the cost of a firm's equity.  In this presentation we give you an understanding of what the model assumes and says, as well as the ability to visualize the cost of equity for any stock.

### Econometrics

Econometrics is statistical analysis applied to questions in economics and finance. The branch is driven by unique situations in economics and finance requiring specialized methods, such as errors-in-variables problems and the need for models of heteroskedasticity in finance.  

##### An Introduction to Correlation Coefficient

The correlation coefficient, which is a measure of the linear relationship between two samples, plays an important role in financial relationships (such as the CAPM).  However what correlation meas is often understood.  The apps let you explore the meaning of correlation betweeen random samples, and also between returns of stocks you choose.

##### An Introduction to the Uses of Monte Carlo Methods in Finance

Monte Carlo is a powerful tool in finance which can be used when a closed-form solution for a problem proves intractable.  This presentation show you cases when Monte Carlo is useful in finance, and lets you interactively run Monte Carlo simulations to value options.

### Trading and Market Structure

Market structure covers how trading is organized, and how this affects liquidity and price discovery.  We also cover how trading takes place in various markets, the types of orders you can enter, and using margin.

#### The Limit Order Book

Trading in the vast majority of markets (US stock, option, futures, bonds) requires interacting with a limit order book.  This is the list of waiting buy and sell orders posted by market makers and other traders.  This interactive presentation will freezes the order book in time, and allows you to enter orders and see their effect on the book.

#### The Pairs Trade

The pairs trade is a widely used market-neutral statistical arbitrage trading strategy.  It is used by hedge funds to provide stable returns which are uncorrelated with the market.  This presentation will enable you to implement the pairs trade for any pair of stock you choose and see your return.

### Derivatives

Derivatives are securities whose payoffs are dependent on other events.  These events can be other security prices or events such as hurricanes and snowfall.  We cover types of derivatives and their valuation, how to use them for risk management and speculation, and the various derivative markets.

#### The Greeks

The *Greeks* measure the sensitivity of Black-Scholes option values to changes in the underlying variables.  They are very important for hedging option books.  This presentation will enable you to see how underlying factors affect the Greeks.

#### An Introduction to Stock Options

This presentation introduces the definition and characteristics of stock options.  It also allows you to interact with characteristics of the option and see how it affects the option's value.  

#### An Introduction to Option and Stock Strategies

Options are often used to reduce the risk of owning a stock (buying a protective put), or alternatively to generate extra income from owning the stock (writing a covered call).  This presentation will cover common stock and option strategies, and allow you to calculate profit and loss for various inputs. 

#### Black-Scholes

The creation of the Black-Scholes model was a watershed event in option and derivative pricing.  The model was the genesis of the idea of pricing derivatives by replication in complete markets.  This presentation introduces the model, allows interaction to see how option prices are affected by inputs, and hopefully motivated further study in derivative pricing.

#### Varying Option Volatility

The Black-Scholes model assumes option volatility is constant across strike price and time.  However consistent deviations from these assumptions are observed---the option smile and variation in the VIX over time.  This presentation provides 3D visualizations of option volatility with actual market data for you to explore. 

### Fixed Income and Other Debt

Fixed income and debt markets cover sovereign (such as US Treasury), municipal, corporate, and mortgage and other consumer debt.  Collectively these markets are very large---the US Treasury market alone is over $18 trillion with about $500 billion per day in average trading volume.  We'll cover trading, valuation, and risk management of these securities.

#### Duration

Duration is a measure of the interest rate risk in a debt security.  It provides a linear approximation of the change in the bond's price for a given change in the bond's yield-to-maturity.This presentation will allow you to visualize the relationship and see how interest rate risk is affected by the bond's terms.

#### Convexity

Convexity is a term for the error in using a linear approximation of the actual (convex) relationship between bond yield and price.  For small changes in yield, convexity is generally small, and conversely for large changes in yield.  This presentation will allow you to see how underlying factors affect convexity.

#### Treasury Debt Risk

This presentation takes a look at recent trends in US Treasury ownership and issuance. These trends are affected by Quantitative Easing and other unconventional monetary policies the US Federal Reserve has enacted since the 2008 financial crisis.

#### Exchange Traded Notes

Exchange traded notes are similar to exchange traded funds, except that they are debt securities so they do not actually have to buy underlying assets in order to match index returns.  We discuss the implications of this regarding the fund's risk and ability to track index returns.

#### For What is the Yield-to-Maturity Used?

This presentation explains the use of the yield-to-maturity in quoting the return on a bond.  However we point out it is not used to find the value (*valuation*) of a bond, but rather simply translate its yield into a price.  

### Foreign Exchange

Foreign exchange markets are enable exchanging currency in support of international trade and investment. In these presentation we learn about the various currencies and derivatives traded in these market.  The derivatives are used to manage risk in cross-border trade and investment.  We also cover arbitrage in the various currency markets.  

#### Foreign Exchange Arbitrage

When arbitrages are possible, they provide a mechanism to determine security and derivative prices.  This presentation will introduce you to three classic arbitrages in foreign exchange and futures markets, and allow you to calculate profits for various inputs.   

#### Foreign Exchange Markets

Foreign exchange markets are extremely important for their ability to facilitate international trade and investment.  However, foreign exchange markets are markedly different from stock and bond markets.  This presentation will introduce you to the organization, structure, and characteristics of foreign exchange markets. 

### Equity 

Equity represents ownership in a corporation, and has a residual claim on corporate earnings.  Along with debt, is the major way in which corporations finance their assets. We'll cover the markets in which equity is traded, the type of trading, and securities comprised of equity.   We'll also cover how the payoff structure (residual claim) affects equity holder preferences for corporate risk taking.  

#### An Introduction to Stock Investments

This presentation will introduce you to the nature of stock and stock trading, as well as a brief introduction to stock market performance.  

#### An Introduction Stock Markets

Stock markets, and how stock is traded, has undergone rapid change in the last 10 to 20 years. We have gone from centralized trading in a few venues, to trading across over a dozen locations across the country. Further, trading has increased in speed up to the limit of physics.

#### Short Selling Stock

If you short sell stock you earn the exact inverse profit than if you had bought stock.  If the stock declines by $1 you gain that dollar, and vice versa.  This presentation explains the mechanics of putting on a short position, and the positions profit and loss.

#### Exchange Traded Funds

Exchange traded funds are open-ended, passively managed, investment funds which generally track an index.  They trade throughout the day like stock, and are known for their low fees.  This presentation will introduce commonly traded ETFs and explore their ability to track their index. 

#### Leveraged Exchange Traded Funds

These are exchange traded funds with built-in leverage---they recreate buying the underlying exchange traded fund on margin. The use of leverage has important implications for the ability of the leveraged exchange traded fund to track a multiple of its underlying index.

### Monetary Policy

Monetary policy is the control of the money supply to achieve goals, such as in the United States, to provide stable prices and maximum employment.  These presentations will cover how monetary policy makers make decisions, as well as the mechanisms used to control the money supply.  

#### Fed Communications

Given the influence the US Federal Reserve has over security markets, the Fed is very careful in its communication with markets.  This interactive presentation covers the manner in which the Fed communicates, and lets you explore various Fed statements and how they have evolved over time.  The presentation will also translate careful Fed statements into everyday language. 

### Commodities

We cover trading and risk management in commodity markets.  Commodities are generally products which serve as raw materials for industrial processes. Examples of commodities are natural gas, wheat, and feeder cattle.

#### Crude Oil Markets

Crude oil plays an important role in the economy.  Oil is an input into most products given its use in transportation.  So oil prices and markets are often watched for their impact on inflation and consumer disposable income.    

#### Cross Hedging

Commodity futures markets are often used by commodity producing and consuming companies to manage risk.  Often, though, a futures contract does not exist to hedge the exact commodity that a firm wants to hedge.  In this case the firm can hedge with a similar commodity---this is *cross-hedging* and it introduces certain risks to the hedge.
