#+TITLE: 5MinuteFinance Quiz Questions
#+OPTIONS: toc:nil


* Derivatives                                                          :done:

** The Greeks							       :done:

1.  The Greeks measure the sensitivity of the ______ price to changes in the underlying variables.

a.  stock's

b.  option's **

c.  bond's

2.  [@2]  Delta can be used to hedge changes in:

a.  time

b.  volatility

c.  stock **

d.  market risk

3.  [@3]  A call option's rho is:

a.  greater than or equal to 0.

b.  less than or equal to 0.

c.  always equal to 0

** Intro Stock Options						       :done:

1.  An option's intrinsic value is:

a.  the value of the option's remaining time.

b.  the value of the option if you would have to exercise it immediately.  **

c.  the price of the option.

2.  [@2] One option contract is for ______ options.

a.  1

b.  100 **

c.  1000

3.  [@3]  A European put option's value can be less than its intrinsic value.

a.  true **

b.  false

** Option/Stock Strategy					       :done:

1.  Options can be used to decrease the risk of a stock position.

a.  true **

b.  false

2.  [@2]  To buy a covered call you:

a.  short the stock and buy a call

b.  buy the stock and sell a call **

c.  buy both a put and a call

3.  [@3]  To buy a protective put you:

a.  buy the stock and a put. **

b.  buy the stock and sell a put.

c.  short the stock and sell a put.

** Black-Scholes						       :done:

1.  The Black-Scholes model requires the stock's expected return as an input.

a.  true

b.  false **

2.  [@2]  Dividend payment _____ the value of a call option, and ______ the value of a put.

a.  increase; increase

b.  increase; decrease

c.  decrease; increase **

d.  decrease; decrease

3.  [@3]  In the Black-Scholes option pricing model volatility is allowed to change over the life of the option.

a.  true

b.  false **

** Varying Option Volatility					       :done:

1.  The dependence of an option’s implied volatility on the option’s moneyness, is known as the option's _____.

a.  frown

b.  smile **

c.  tenor

2.  [@2]  Option implied volatility is generally higher for:

a.  in-the-money puts

b.  out-of-the-money puts **

3.  [@3]  The option smile tends to be constant across tenor and time.

a.  true

b.  false **

* Econometrics                                                         :done:

** Correlation							       :done:

1.  The correlation coefficient ranges between -1 and 1.

a.  true **

b.  false

2.  [@2]  Linear transformations affect the correlation coefficient.

a.  true

b.  false **

3.  [@3]  No stocks have negative return correlations.

a.  true

b.  false **

** Monte Carlo							       :done:

1.  Monte Carlo provides an exact solution.

a.  true

b.  false **

2.  [@2]  Monte Carlo methods can only be used for European options.

a.  true

b.  false **


3.  [@3]  Even if we have a closed-form continuous time solution, Monte Carlo may provide a more accurate value if the option's payoff is calculated at discrete points.

a.  true **
b.  false

* Fixed Income/Other Debt					       :done:
  
** Duration                                                            :done:
   
1.  Duration is a measure of:

a.  the time until a bond matures.

b.  the time until the next bond payment.

c.  the bond's interest rate risk. **

2.  [@2]  Duration is an approximate, not exact, measure.
   
a.  true **

b.  false

3.  [@3]  As a bond's yield-to-maturity increases, the bond's duration:

a.  increases

b.  decreases **

c.  stays the same

** Convexity							       :done:
   
1.  Convexity benefits bond owners:

a.  true **

b.  false

2.  [@2]  Using duration and convexity is more accurate than duration alone.

a.  true **

b.  false

3.  [@3] As the bond's yield-to-maturity rises, the bond's convexity:

a.  increases **

b.  decreases

c.  stays the same

* Fundamentals

* Portfolio Finance                                                    :done:

** Intro: Portfolio Performance                                        :done:
   
1.  We would prefer our portfolio's Sharpe Ratio to be:

a.  higher **

b.  lower

c.  equal to zero

2.  [@2] The denominator in the Treynor Ratio is the asset's beta coefficient, which is more appropriate than the standard deviation for:

a.  portfolios of many assets

b.  single assets **

3.  [@3] The 'Information Ratio' divides alpha by:

a.  the portfolio's market risk.

b.  the portfolio's residual (non-market) risk **  

** Portfolio Optimization                                              :done:

1.  Which of the following characteristic of an asset's return distribution is used in Markowitz portfolio optimization?

a.  Kurtosis

b.  mean **

c.  skewness

2.  [@2]  Diversification can eliminate all risk from a portfolio of assets.

a.  true

b.  false **

3.  [@3]  Diversification benefits from negative correlations between assets.

a.  true **

b.  false

* Risk								       :done:

** Risk and Value-At-Risk                                              :done:

1.  Using the standard deviation as a measure of risk, makes no assumptions on the stock process.

a.  true

b.  false **

2.  [@2]  If we assume a normal distribution we don't have to use historical data.

a.  true

b.  false **

3.  [@3]  Value-at-Risk is affected by the amount of historical data you use.

a.  true **

b.  false

** Risk Over Time                                                      :done:
   
1.  An asset's risk is constant through time.

a.  true

b.  false **

2.  [@2]  In markets, we tend to see volatility cluster (high volatility follows high volatility).  

a.  true **

b.  false

3.  [@3]  We can observe market forecasts of an asset's volatility by looking at:

a.  the asset's beta

b.  implied volatility in options traded on the asset **

c.  the asset's standard deviation

** The VIX Index                                                       :done:
   
1.  The VIX provides an estimate of the market expectation of volatility in the S&P 500 over the next 30 days, using:

a.  a GARCH(1,1) model

b.  implied volatility from options on the S&P 500 **

c.  a Markov-Switching model

2.  [@2]  If the VIX is 12, this means there is a 68% chance that the absolute value of the S&P 500's return will be less than:

a.  2.55% over the next 30 days.

b.  4.33% over the next 30 days. **

c.  8.75% over the next 30 days.

3.  [@3] The higher the VIX, the more ______ there is among market participants.

a.  fear **

b.  calm 

** VVIX:  The Vol of Vol					       :done:

1.  The VVIX is measure of the volatility of an index that itself measures volatility.

a.  true **

b.  false

2.  [@2]  The VVIX behaves like a random walk process.

a.  true

b.  false **

3.  [@3]  The VVIX is ______ correlated with S&P 500 returns.

a.  positively

b.  negatively **

* Trading and Market Structure                                         :done:
  
** The Limit Order Book                                                :done:
   
1.  A market order provides liquidity to the market.

a.  true

b.  false **

2.  [@2] Limit orders are guaranteed to be filled.

a.  true

b.  false **

3.  [@3]  The ability to transact quickly without moving the asset's price is known as:

a.  liquidity **

b.  solidity

c.  volatility

d.  solvency

** The Pairs Trade                                                     :done:

1. In the pairs trade we are speculating on firm specific risk, and hedging out market risk. 
   
a.  true **

b.  false

2.  [@2] The pairs trade is inherently risky.

a.  true

b.  false **

3.  [@3]  It is important to estimate the model parameters over a different interval than you trade the model.

a.  true **

b.  false 
* Corporate Finance  
** Intro Financial Statements					       :done:

1.  Which financial statement is a snapshot in time?

a.  income statement

b.  balance sheet **

c.  statement of cash flows

2.  [@2] A firm's balance sheet lists assets at their market values.

a.  true

b.  false **

3.  [@3]  Which is a noncash item on the income statement?

a.  cost of goods sold

b.  taxes

c.  depreciation **

** Financial Ratios						       :done:

1. Financial Ratios are commonly used to compare firms in different industries.

a.  true

b.  false **

2.  [@2] These measure the firm's ability to meet its debt obligations over the short-term.

a.  Profitability Ratios

b.  Liquidity Ratios **

c.  Market-Value Ratios

3.  [@3] The Du-Pont Identity decomposes firm Return-on-Equity into Profit Margin times Total Asset Turnover times the:

a.  Current Ratio

b.  Times-Interest-Earned Ratio.

c.  Market-to-Book Ratio.

d.  Equity Multiplier **
   
** TVM Single CFs						       :done:

1.  The value of money is a function of time.

a.  true **

b.  false

2.  [@2] The higher the discount rate, the _____ the present value.

a.  higher

b.  lower **

3.  [@3]  The more periods, the _____ the future value.

a.  higher **

b.  lower

** TVM Multiple CFs						       :done:

1.  A financial contract which makes a fixed payment, every period, for a fixed number of periods is:

a.  a perpetuity

b.  a growing perpetuity

c.  an annuity **

d.  a growing annuity

2.  [@2] Because a perpetuity has an infinite number of payments, it also has an infinite value.

a.  true

b.  false **

3.  [@3]  Which of the following is an annuity?

a.  fixed-rate mortgage **

b.  common stock

c.  preferred stock

** OCF								       :done:

1.  The calculation of accounting profit included noncash deductions.

a.  true **

b.  false

2. [@2]  If EBIT, Depreciation, and Taxes are $1000, $100, and $200 respectively, then Operating Cash Flow is:

a.  $1000

b.  $900 **

c.  $800

d.  $700

3. [@3] We should not include interest, because it is a financing, and not operating, expense.

a.  true **

b.  false

** NPV and IRR							       :done:

1.  If a project's NPV is $100,000, this means that if we accept the project:

a.  the market value of the firm's equity will increase by $1000. **

b.  the market value of the firm's equity will decrease by $1000.

c.  the market value of the firm's equity will be unchanged.

2. [@2]  There is guaranteed to be one IRR.

a.  true

b.  false **

3. [@3]  If a project's cash flows are conventional, and we are not ranking it against another project, then NPV and IRR will give the same accept/reject result.

a.  true **

b.  false

5MF: note, in the choosing between projects section, the IRR is messed up.
   
** Intro Stock Val						       :done:

1.  Say a stock pays a constant dividend of $20 per share, and the discount rate is 10%, then the stock's value is:

a.  $100

b.  $150

c.  $200 **

d.  $250

2. [@2]  Say a stock's next dividend is $5, and it will grow at a constant 8%.  If the discount rate is 4%, the stock's price is:

a.  $100

b.  $125 **

c.  $150

d.  $200


3. [@3]  If we assume a stock's dividend grows at a constant rate, this implies the stock's price also increases at a constant rate.

a.  true **

b.  false

** Intro Bond Val

1.  If a bond's YTM is above its coupon rate, then its price is:

a.  greater than par.

b.  equal to par.

c.  less than par. **

2. [@2]  Switching from annual to semiannual interest (all else constant), always lowers the value of a bond.

a.  true

b.  false **

3. [@3] If we buy a coupon bond and hold it until maturity, we are guaranteed to earn the YTM.

a.  true

b.  false ** 

** CAPM

1.  

2. [@2]  

3. [@3]  

** Compounding/EAR

1.  

2. [@2]  

3. [@3]  

** Goal Fin Mgmt

1.  

2. [@2]  

3. [@3]  

** Dividends

1.  

2. [@2]  

3. [@3]  

** Balance Sheet Identity

1.  

2. [@2]  

3. [@3]  

** MM Props

1.  

2. [@2]  

3. [@3]  

** WACC

1.  

2. [@2]  

3. [@3]  

** Capital Structure

1.  

2. [@2]  

3. [@3]  
   
